language: python

python:
  - pypy
  - pypy3
  - 3.5
  - 2.7
  - 3.3
  - 3.4
  - nightly

install:
  - travis_retry pip install pillow
  - travis_retry pip install -r testsuite/requirements.txt

script:
  - cd testsuite
  - ./run.py --help
  - ./run.py -s 512x512 -n 1  load convert scale blur composition rotate_right
  - ./run.py -s 512x512 -n 1  wand_load wand_scale wand_rotate_right
  - ./run.py -s 512x512 -n 1  cv2_load cv2_scale cv2_blur cv2_rotate_right

after_success:
  - pwd
  - travis_retry pip install pep8 pyflakes
  - pep8 --statistics --count .
  - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
