language: python

python:
  - pypy
  - pypy3
  - 3.6
  - 2.7
  - 3.5
  - 3.4
  - 3.3
  - nightly

install:
  - travis_retry pip install pillow
  - travis_retry pip install -r testsuite/requirements.txt

script:
  - cd testsuite
  - ./run.py --help
  - ./run.py -s 512x512 -n 1 --json  load convert scale blur composition rotate_right
  - ./run.py -s 512x512 -n 1 --json  wand_load wand_convert wand_scale wand_blur wand_composition wand_rotate_right

after_success:
  - pwd
  - travis_retry pip install pep8 pyflakes
  - pep8 --statistics --count .
  - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
