language: python

python:
  - pypy
  - pypy3
  - 3.6
  - 2.7
  - nightly

install:
  - travis_retry pip install pillow
  - travis_retry pip install -r testsuite/requirements.txt

script:
  - cd testsuite
  - ./run.py --help
  - ./run.py -s 512x512 -n 1 --json  load convert composition rotate_right scale blur filter allocate crop full_cycle
  - ./run.py -s 512x512 -n 1 --json  wand_load wand_convert wand_scale wand_blur wand_composition wand_rotate_right wand_full_cycle

after_success:
  - pwd
  - travis_retry pip install pycodestyle pyflakes
  - pycodestyle --statistics --count .
  - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
